# This file was generated by GoReleaser. DO NOT EDIT.
cask "k8s-d2" do
  name "k8s-d2"
  desc "Generate D2 diagrams from Kubernetes cluster topology"
  homepage "https://github.com/vieitesss/k8s-d2"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "k8sdd"

  on_macos do
    on_intel do
      url "https://github.com/vieitesss/k8s-d2/releases/download/v#{version}/k8s-d2_#{version}_Darwin_x86_64.tar.gz"
      sha256 "00e02e4863fecd3a432f18a4c291ce8a73c7bc94538fa6b15c96a054f86ddecd"
    end
    on_arm do
      url "https://github.com/vieitesss/k8s-d2/releases/download/v#{version}/k8s-d2_#{version}_Darwin_arm64.tar.gz"
      sha256 "27abf1520d9c8125d8bfdbe125af9a257268a66c2548fcf1a950d78cf144d69b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vieitesss/k8s-d2/releases/download/v#{version}/k8s-d2_#{version}_Linux_x86_64.tar.gz"
      sha256 "4ff131b4008652fe4a99a8bcf40db78e835dc6fb337c7a0ec5157038a823afc2"
    end
    on_arm do
      url "https://github.com/vieitesss/k8s-d2/releases/download/v#{version}/k8s-d2_#{version}_Linux_arm64.tar.gz"
      sha256 "7e738cf95a639f8cb4f98a4b6bc91c9abd58365568e09f8fffdf23f36d637b5e"
    end
  end

  # No zap stanza required
end
